### ISSUE TITLE
Is it possible to add ptr hook check?

### ISSUE THREAD

**Issue by 16hex-Dumb** [SmoLL-iCe/hookWolf#1]

**Comment by 16hex-Dumb** [comment]
Like checking all RVAs?

**Comment by SmoLL-iCe** [comment]
Currently I don't intend to do anything like that, and I didn't even intend to do it here at the beginning.
but possible is, just parse it using the entry base realocation.
then you compare if that current offset of the running module is equal to the offset that is stored.
